import type { ParsedCorpus } from "./qa-wiki-parse.ts";

export type WikiSummary = Readonly<Record<string, number>>;
export type MutableMetrics = Record<string, number>;

export const hardMetricNames = [
  "weak-verified",
  "legal-date-missing",
  "unsupported-derived-claims",
  "duplicate-canonical-keys",
  "dangling-links",
  "dangling-ledger-ids",
  "frontmatter-keyset-mismatches",
  "new-frontmatter-keys",
  "handwritten-index-outcomes",
  "unqualified-numerical-claims",
  "recovery-state-conflations",
  "undocumented-coverage-gaps",
  "unresolved-report-citations",
  "pii-pattern-hits",
  "overlong-excerpts",
  "malformed-inputs",
  "derived-claim-cycles",
  "excerpt-digest-mismatches",
  "embedded-source-text-fields",
  "backdated-render-timestamps",
  "report-proposition-mismatches",
  "missing-report-assurances",
  "unadjudicated-statistic-definitions",
  "missing-saturation-ledger",
  "inadequate-terminal-query-mappings",
  "unrelated-terminal-query-mappings",
  "invalid-terminal-query-receipts",
  "invalid-terminal-query-chronology",
  "generic-terminal-query-adjudications",
  "unbound-terminal-result-occurrences",
  "insufficient-terminal-waves",
  "duplicate-terminal-query-manifests",
  "overlapping-terminal-queries",
  "terminal-candidate-queue",
  "terminal-material-novelty",
  "unlinked-coverage-matrix",
  "broken-saturation-chain",
  "missing-saturation-predecessors",
  "cyclic-saturation-chain",
  "forward-saturation-predecessors",
  "skipped-saturation-predecessors",
  "missing-candidate-inventory",
  "candidate-identity-count-mismatch",
  "candidate-occurrence-count-mismatch",
  "duplicate-candidate-identities",
  "duplicate-candidate-occurrence-ids",
  "orphan-candidate-occurrences",
  "double-linked-candidate-occurrences",
  "missing-candidate-occurrences",
  "missing-candidate-identities",
  "candidate-inventory-queue",
  "candidate-provenance-mismatches",
  "candidate-provenance-count-mismatch",
  "terminal-candidate-count-mismatch",
  "invalid-terminal-candidate-reviews",
  "missing-public-render",
  "public-render-file-mismatches",
  "public-render-citation-mismatches",
  "duplicate-public-ids",
  "seed-audit-mismatches",
  "report-structure-mismatches",
  "banned-report-inferences",
  "missing-report-render",
  "report-render-mismatches",
  "report-assertion-mismatches",
  "unregistered-report-assertions",
  "repository-artifact-mismatches",
  "repository-audit-mismatches",
] as const;

export function createMetrics(corpus: ParsedCorpus): MutableMetrics {
  return Object.fromEntries([
    ...hardMetricNames.map((name) => [name, 0]),
    ["markdown-files", corpus.files.length],
    ["ledger-records", corpus.records.length],
    ["sources", 0],
    ["observations", 0],
    ["claims", 0],
    ["verifications", 0],
    ["coverage-records", 0],
    ["seed-audit-files", 0],
    ["seed-disposition-records", 0],
    ["coverage-matrix-cells", 0],
    ["saturation-records", 0],
    ["terminal-zero-novelty-waves", 0],
    ["distinct-terminal-query-manifests", 0],
    ["terminal-query-replays", 0],
    ["cell-adequate-terminal-waves", 0],
    ["terminal-receipted-cell-queries", 0],
    ["coverage-matrix-linked-waves", 0],
    ["documented-incomplete-saturation", 0],
    ["candidate-identities", 0],
    ["candidate-occurrences", 0],
    ["candidate-identity-records", 0],
    ["candidate-occurrence-records", 0],
    ["candidate-provenance-links", 0],
    ["terminal-candidate-records", 0],
    ["candidate-queue-count", 0],
    ["terminal-candidate-reviews", 0],
    ["public-render-files", 0],
    ["public-render-citations", 0],
    ["report-assertions", 0],
    ["repository-sources", 0],
    ["repository-observations", 0],
    ["repository-claims", 0],
  ]);
}

export function increment(metrics: MutableMetrics, name: string, amount = 1): void {
  metrics[name] = (metrics[name] ?? 0) + amount;
}
