export const IPC_CHANNELS = Object.freeze({
  createCase: "case:create",
  analyzeEvidence: "evidence:analyze",
  confirmOcrFacts: "evidence:confirm-ocr-facts",
  advanceCriminal: "workflow:criminal:advance",
  advanceCivil: "workflow:civil:advance",
  enforcementChoices: "workflow:enforcement:choices",
  guidance: "guidance:korean-law",
  openOfficialSource: "official-source:open",
  openTrustedAuthentication: "trusted-authentication:open",
  codexStatus: "codex:status",
  codexLogin: "codex:login",
  codexSuggestion: "codex:suggestion",
  agentCaseOpen: "agent:case:open",
  agentArtifactOpen: "agent:artifact:open",
  agentRunStart: "agent:run:start",
  agentRunGet: "agent:run:get",
  agentRunList: "agent:run:list",
  agentRunPause: "agent:run:pause",
  agentRunResume: "agent:run:resume",
  agentRunCancel: "agent:run:cancel",
  agentApprovalDecision: "agent:approval:decision",
  agentRunSubscribe: "agent:run:subscribe",
  agentRunEvent: "agent:run:event",
});
